version: '3.8'
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        command: mysqld
        ports:
            - 33061:3306
        volumes:
            - ~/apps/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=S3cret
            - MYSQL_PASSWORD=An0thrS3crt
            - MYSQL_USER=mysql_user
            - MYSQL_DATABASE=jwt_dbase
    
    mysql-workbench:
        image: lscr.io/linuxserver/mysql-workbench:latest
        container_name: mysql-workbench
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /apps/config:/config
        ports:
            - 3000:3000
        cap_add:
            - IPC_LOCK
        restart: unless-stopped